### ISSUE TITLE
Should react-object-inspector be a peerDependency?

### ISSUE THREAD

**Issue by gaearon** [alexkuz/react-transform-debug-inspector#2]
Currently, just adding

``` js
import 'style!css!react-object-inspector/react-object-inspector.css';
```

won't do because `react-object-inspector` itself is inside `react-transform-debug-inspector`'s `node_modules`.

**Comment by alexkuz** [comment]
@gaearon yeah, I think I'll just make my own css here, based on `react-object-inspector.css` (I'm not so happy with default layout, feels like it could be better)

**Comment by gaearon** [comment]
:+1:
